### ISSUE TITLE
EX7-Additional Ellipse Azimuthの計算間違い

### ISSUE THREAD

**Issue by arms22** [nbtk/azarashi#13]
EX7-Additional Ellipse Azimuthの計算が間違っているようです。

https://github.com/nbtk/azarashi/blob/ea521f886d65a6b33b47642899e495ac0c8d1213/azarashi/qzss_dcr_lib/decoder/qzss_dcx_decoder.py#L411

正しくは

` self.ex7_ellipse_azimuth = -90 + 180 / 128 * camf.ex7 `

ではないでしょうか？

**Comment by nbtk** [comment]
報告ありがとうございます。
ご指摘いただいた箇所、間違っていました。
テストして週明けにリリース予定です。

**Comment by arms22** [comment]
ご対応ありがとうございます！
デコード結果突き合わせて確認するのにめちゃくちゃ助かっています！

**Comment by nbtk** [comment]
役に立っているようならうれしいです！
こちらこそ、ありがとうございます。

直しました。
https://github.com/nbtk/azarashi/releases/tag/v0.11.0
